#!/bin/sh

# Copyright (c) 2011 Michiel Detailleur
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# TODO:
#   * add a quiet output mode (no extra output, just the output from the jexec call)
#   * add an option to also run the command on the host
#   * add an option to clear the environment before running the command? (env - command)
#   * add an option to run command(s) in a shell? or is sh -c 'command' easy enough?
#   * add an option to ask for confirmation on each jail before running the command
#       (handy for selective tasks or when running commands that overwrite output and
#        make you not see the jail name that the command is currently running on)



# Link file descriptor #6 with stdin. Saves stdin.
#exec 6<&0

jls host.hostname jid ip4.addr ip6.addr | sort | while read hostname jid ips
do
    echo '===>>>' $hostname \($jid\) \($ips\)
    # Restore stdin from fd #6 and close fd #6
    # to free it for other processes to use.
    # Stdin was lost when using the pipes for sort and while.
    #exec 0<&6 6<&-
    # This makes sure that jexec below receives the same
    # stdin as jexec_all.
    # This fixes expected behavior when using commands that
    # expect tty input or when doing input rerouting on the
    # jexec_all command and expecting the same behavior as
    # from the standard jexec command.
    #jexec $jid "$@" 0<&6
    jexec $jid "$@" </dev/tty
    echo
    # THIS IS ALL PRETTY COOL AND INTERESTING,
    # BUT THE ONLY UNAMBIGOUS BEHAVIOUR IS IF
    # JEXEC GETS /dev/tty AS INPUT.
    # FILES OR PIPES DONT MAKE SENSE:
    # ONLY THE FIRST JAIL WILL RECEIVE IT
    # OR SHOULD THEY ALL RECEIVE IT? WE CAN'T REPLAY THE INPUT!
    # OR SHOULD WE tee IT? BUT THEN THE COMMANDS NEED TO RUN IN
    # PARALLEL? WHAT DO WE DO WITH THE OUTPUT THEN???
done
